POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Post Test",
    "number": "040-000111"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "",
    "number": "040-000111"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Same test",
    "number":""
}